heapdraw: main.o Heap.o draw.o
	g++ main.o Heap.o draw.o -lglut -o heapdraw
main.o: main.cpp
	g++ main.cpp -o main.o -c
Heap.o: Heap.cpp
	g++ Heap.cpp -o Heap.o -c
draw.o: draw.cpp
	g++ draw.cpp -o draw.o -c
	
